#cloud-config

# Set TimeZone and Locale
timezone: Europe/Madrid
locale: es_ES.UTF-8

# Hostname
hostname: {0}

manage_etc_hosts: localhost

## Add docker and vagrant apt repository
## GPG keys need to be added
## Docker: curl -sL https://download.docker.com/linux/ubuntu/gpg | gpg
## Hashicorp: curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg
apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    vagrant.list:
      source: deb [arch=amd64] https://apt.releases.hashicorp.com $RELEASE main
      keyid: E8A032E094D8EB4EA189D270DA418C88A3219F7B

# Update packge cache

package_update: true
# Install docker and python packages
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - git
  - software-properties-common
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - build-essential
  - python3-dev
  - python3-pip
  - python3-setuptools
  - python3-yaml
  - qemu
  - qemu-kvm
  - libvirt-clients
  - libvirt-daemon-system
  - virtinst
  - bridge-utils
  - vagrant
  - libxslt-dev
  - libxml2-dev
  - libvirt-dev
  - zlib1g-dev
  - ruby-dev
  - ruby-libvirt
  - ebtables
  - dnsmasq-base
  - libguestfs-tools 

# Enable ipv4 forwarding
write_files:
  - path: /etc/sysctl.d/enabled_ipv4_forwarding.conf
    content: |
      net.ipv4.conf.all.forwarding=1

# create the docker and libvirt group
groups:
  - docker
  - libvirt

# Users. Remove default (ubuntu)
users:
  - name: ricsanfre
    gecos: Ricardo Sanchez
    primary_group: users
    groups: [docker, libvirt]
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: true
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAusTXKfFoy6p3G4QAHvqoBK+9Vn2+cx2G5AY89WmjMikmeTG9KUseOCIAx22BCrFTNryMZ0oLx4u3M+Ibm1nX76R3Gs4b+gBsgf0TFENzztST++n9/bHYWeMVXddeV9RFbvPnQZv/TfLfPUejIMjFt26JCfhZdw3Ukpx9FKYhFDxr2jG9hXzCY9Ja2IkVwHuBcO4gvWV5xtI1nS/LvMw44Okmlpqos/ETjkd12PLCxZU6GQDslUgGZGuWsvOKbf51sR+cvBppEAG3ujIDySZkVhXqH1SSaGQbxF0pO6N5d4PWus0xsafy5z1AJdTeXZdBXPVvUSNVOUw8lbL+RTWI2Q== ubuntu@mi_pc
# Install Ansible
runcmd:
  - su - ricsanfre -c "pip3 install --upgrade pip setuptools"
  - su - ricsanfre -c "pip3 install ansible"
  - su - ricsanfre -c "pip3 install yamllint ansible-lint"
  - su - ricsanfre -c "pip3 install molecule[docker] molecule-vagrant python-vagrant"
  - su - ricsanfre -c "vagrant plugin install vagrant-libvirt" 
  - su - ricsanfre -c "vagrant plugin install vagrant-mutate"
